create table if not exists public.translation_access_state (
  user_id uuid primary key,
  trial_started_at timestamptz,
  trial_ends_at timestamptz,
  paid_access_started_at timestamptz,
  paid_access_ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.translation_access_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  request_key text not null,
  module text not null,
  access_mode text not null,
  tokens_charged integer not null default 0,
  access_ends_at timestamptz,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, request_key)
);

create index if not exists translation_access_requests_user_created_idx
  on public.translation_access_requests (user_id, created_at desc);

alter table public.translation_access_state enable row level security;
alter table public.translation_access_requests enable row level security;

revoke all on public.translation_access_state from anon, authenticated;
revoke all on public.translation_access_requests from anon, authenticated;
grant all on public.translation_access_state to service_role;
grant all on public.translation_access_requests to service_role;

drop function if exists public.claim_translation_daily_access(uuid, text, text);

create function public.claim_translation_daily_access(
  p_user_id uuid,
  p_request_key text,
  p_module text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_request_key text := nullif(btrim(coalesce(p_request_key, '')), '');
  v_module text := left(coalesce(nullif(btrim(p_module), ''), 'translation'), 120);
  v_state public.translation_access_state%rowtype;
  v_previous jsonb;
  v_tokens_before bigint;
  v_tokens_after bigint;
  v_result jsonb;
begin
  if p_user_id is null then
    raise exception 'user_id_required';
  end if;

  if v_request_key is null then
    raise exception 'request_key_required';
  end if;

  if length(v_request_key) > 200 then
    raise exception 'request_key_too_long';
  end if;

  select result
    into v_previous
    from public.translation_access_requests
   where user_id = p_user_id
     and request_key = v_request_key
   limit 1;

  if v_previous is not null then
    return v_previous || jsonb_build_object('idempotent_replay', true);
  end if;

  insert into public.translation_access_state (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  select *
    into v_state
    from public.translation_access_state
   where user_id = p_user_id
   for update;

  if v_state.trial_started_at is null then
    update public.translation_access_state
       set trial_started_at = v_now,
           trial_ends_at = v_now + interval '7 days',
           updated_at = v_now
     where user_id = p_user_id
     returning * into v_state;

    v_result := jsonb_build_object(
      'ok', true,
      'charged', false,
      'access_mode', 'trial_started',
      'tokens_charged', 0,
      'trial_started_at', v_state.trial_started_at,
      'trial_ends_at', v_state.trial_ends_at,
      'access_ends_at', v_state.trial_ends_at,
      'module', v_module,
      'request_key', v_request_key
    );

  elsif v_state.trial_ends_at is not null and v_now < v_state.trial_ends_at then
    v_result := jsonb_build_object(
      'ok', true,
      'charged', false,
      'access_mode', 'trial_active',
      'tokens_charged', 0,
      'trial_started_at', v_state.trial_started_at,
      'trial_ends_at', v_state.trial_ends_at,
      'access_ends_at', v_state.trial_ends_at,
      'module', v_module,
      'request_key', v_request_key
    );

  elsif v_state.paid_access_ends_at is not null and v_now < v_state.paid_access_ends_at then
    v_result := jsonb_build_object(
      'ok', true,
      'charged', false,
      'access_mode', 'paid_active',
      'tokens_charged', 0,
      'paid_access_started_at', v_state.paid_access_started_at,
      'paid_access_ends_at', v_state.paid_access_ends_at,
      'access_ends_at', v_state.paid_access_ends_at,
      'module', v_module,
      'request_key', v_request_key
    );

  else
    update public.profiles
       set tokens = coalesce(tokens, 0) - 5
     where id::text = p_user_id::text
       and coalesce(tokens, 0) >= 5
     returning coalesce(tokens, 0) + 5, coalesce(tokens, 0)
          into v_tokens_before, v_tokens_after;

    if v_tokens_after is null then
      select coalesce(tokens, 0)
        into v_tokens_before
        from public.profiles
       where id::text = p_user_id::text
       limit 1;

      return jsonb_build_object(
        'ok', false,
        'charged', false,
        'reason', 'insufficient_tokens',
        'code', 'INSUFFICIENT_TOKENS',
        'required_tokens', 5,
        'tokens_charged', 0,
        'tokens_before', coalesce(v_tokens_before, 0),
        'tokens_after', coalesce(v_tokens_before, 0),
        'module', v_module,
        'request_key', v_request_key
      );
    end if;

    update public.translation_access_state
       set paid_access_started_at = v_now,
           paid_access_ends_at = v_now + interval '24 hours',
           updated_at = v_now
     where user_id = p_user_id
     returning * into v_state;

    insert into public.wallet_tx (user_id, type, amount, reason, meta)
    values (
      p_user_id,
      'usage_translation_day',
      -5,
      'Tum ceviri modulleri - 24 saat',
      jsonb_build_object(
        'source_module', v_module,
        'billing_model', 'translation_daily_access_v1',
        'request_key', v_request_key,
        'tokens_before', v_tokens_before,
        'tokens_after', v_tokens_after,
        'tokens_charged', 5,
        'access_started_at', v_state.paid_access_started_at,
        'access_ends_at', v_state.paid_access_ends_at
      )
    );

    v_result := jsonb_build_object(
      'ok', true,
      'charged', true,
      'access_mode', 'paid_started',
      'tokens_charged', 5,
      'tokens_before', v_tokens_before,
      'tokens_after', v_tokens_after,
      'paid_access_started_at', v_state.paid_access_started_at,
      'paid_access_ends_at', v_state.paid_access_ends_at,
      'access_ends_at', v_state.paid_access_ends_at,
      'module', v_module,
      'request_key', v_request_key
    );
  end if;

  insert into public.translation_access_requests (
    user_id,
    request_key,
    module,
    access_mode,
    tokens_charged,
    access_ends_at,
    result
  ) values (
    p_user_id,
    v_request_key,
    v_module,
    coalesce(v_result->>'access_mode', 'unknown'),
    coalesce((v_result->>'tokens_charged')::integer, 0),
    nullif(v_result->>'access_ends_at', '')::timestamptz,
    v_result
  )
  on conflict (user_id, request_key) do nothing;

  return v_result;
end;
$$;

revoke all on function public.claim_translation_daily_access(uuid, text, text) from public, anon, authenticated;
grant execute on function public.claim_translation_daily_access(uuid, text, text) to service_role;

create or replace function public.get_translation_daily_access_status(
  p_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_state public.translation_access_state%rowtype;
  v_tokens bigint := 0;
  v_mode text := 'not_started';
  v_access_ends_at timestamptz;
begin
  select * into v_state
    from public.translation_access_state
   where user_id = p_user_id;

  select coalesce(tokens, 0) into v_tokens
    from public.profiles
   where id::text = p_user_id::text
   limit 1;

  if v_state.user_id is not null then
    if v_state.trial_ends_at is not null and v_now < v_state.trial_ends_at then
      v_mode := 'trial_active';
      v_access_ends_at := v_state.trial_ends_at;
    elsif v_state.paid_access_ends_at is not null and v_now < v_state.paid_access_ends_at then
      v_mode := 'paid_active';
      v_access_ends_at := v_state.paid_access_ends_at;
    else
      v_mode := 'payment_required';
    end if;
  end if;

  return jsonb_build_object(
    'ok', true,
    'access_mode', v_mode,
    'access_active', v_access_ends_at is not null and v_now < v_access_ends_at,
    'access_ends_at', v_access_ends_at,
    'trial_started_at', v_state.trial_started_at,
    'trial_ends_at', v_state.trial_ends_at,
    'paid_access_started_at', v_state.paid_access_started_at,
    'paid_access_ends_at', v_state.paid_access_ends_at,
    'tokens', coalesce(v_tokens, 0),
    'daily_cost', 5
  );
end;
$$;

revoke all on function public.get_translation_daily_access_status(uuid) from public, anon, authenticated;
grant execute on function public.get_translation_daily_access_status(uuid) to service_role;
